config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :pages, except: [:show]
  end

  root 'application#index'

  get ':id' => 'pages#show', as: 'page'

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/page.rb
class Admin::Page < ActiveRecord::Base
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < ApplicationController
  before_action :set_admin_page, only: [:edit, :update, :destroy]

  # GET /admin/pages
  # GET /admin/pages.json
  def index
    @admin_pages = Admin::Page.all
  end

  # GET /admin/pages/new
  def new
    @admin_page = Admin::Page.new
  end

  # GET /admin/pages/1/edit
  def edit
  end

  # POST /admin/pages
  # POST /admin/pages.json
  def create
    @admin_page = Admin::Page.new(admin_page_params)

    respond_to do |format|
      if @admin_page.save
        format.html { redirect_to admin_pages_url, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @admin_page }
      else
        format.html { render :new }
        format.json { render json: @admin_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/pages/1
  # PATCH/PUT /admin/pages/1.json
  def update
    respond_to do |format|
      if @admin_page.update(admin_page_params)
        format.html { redirect_to admin_pages_url, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_page }
      else
        format.html { render :edit }
        format.json { render json: @admin_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/pages/1
  # DELETE /admin/pages/1.json
  def destroy
    @admin_page.destroy
    respond_to do |format|
      format.html { redirect_to admin_pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_page
      @admin_page = Admin::Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_page_params
      params.require(:admin_page).permit(:name, :parent_id, :lft, :rgt, :depth, :structure, :template)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = Admin::Page.find(params[:id])
    render @page.template
  end
end

app/helpers/admin/pages_helper.rb
module Admin::PagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/pages/_form.html.slim
= form_for(@admin_page, :html => { :class => "form-horizontal" }) do |f|
  - if @admin_page.errors.any?
    .alert.alert-danger.alert-dismissable
      button.close type="button" data-dismiss="alert" aria-hidden="true" 
        | &times;
      h4= "#{pluralize(@admin_page.errors.count,"error")} prohibited this admin_page from being saved:"
      ul
        - @admin_page.errors.full_messages.each do |msg|
          li= msg
  .form-group
    = f.label :name, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :name, :class => "form-control"
  .form-group
    = f.label :parent_id, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.number_field :parent_id, :class => "form-control"
  .form-group
    = f.label :structure, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :structure, :class => "form-control", :disabled => true
  .form-group
    = f.label :template, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.select :template, [['One Column', :one_column]], {}, {:class => "form-control"}
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit :class => "btn btn-primary"

app/views/admin/pages/edit.html.slim
.page-header
  = link_to admin_pages_path, :class => 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to @admin_page, :class => 'btn btn-primary' do
    span.glyphicon.glyphicon-info-sign
    |  Show 
  h1
    | Editing 
    | admin_page

= render 'form'

app/views/admin/pages/index.html.slim
.page-header
  = link_to new_admin_page_path, :class => 'btn btn-primary' do 
    span.glyphicon.glyphicon-plus
    |  New #{Admin::Page.model_name.human.pluralize}
  h1
    | Listing #{Admin::Page.model_name.human.pluralize}

.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th
          | Name
        th
        th
        th
    tbody.nestable
      - @admin_pages.each do | admin_page |
        tr
          td
            = admin_page.name
          td
            = link_to 'Show', page_path(admin_page)
          td
            = link_to 'Edit', edit_admin_page_path(admin_page) 
          td
            = link_to 'Destroy', admin_page, method: :delete, data: { confirm: 'Are you sure?' } 

app/views/admin/pages/new.html.slim
.page-header
  = link_to admin_pages_path, :class => 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  h1
    | New 
    | admin_page

= render 'form'

app/views/admin/pages/show.html.slim
.page-header
  = link_to admin_pages_path, :class => 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to edit_admin_page_path(@admin_page), :class => 'btn btn-primary' do 
    span.glyphicon.glyphicon-pencil
    |  Edit 
  h1
    | Show admin_page
dl.dl-horizontal
  dt
    | Name:
  dd
    = @admin_page.name
  dt
    | Parent:
  dd
    = @admin_page.parent_id
  dt
    | Lft:
  dd
    = @admin_page.lft
  dt
    | Rgt:
  dd
    = @admin_page.rgt
  dt
    | Depth:
  dd
    = @admin_page.depth
  dt
    | Structure:
  dd
    = @admin_page.structure

app/views/application/index.html.slim
h1 Hello World!

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    title
      | Starter Template for Bootstrap
    meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
    meta name="description" content=""
    meta name="author" content=""
    /! HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-collapse"
            span.sr-only
              | Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to "Project name", "#", :class => "navbar-brand"
        .collapse.navbar-collapse
          ul.nav.navbar-nav
            li.active
              a href="#"
                | Home
            li
              a href="#about" 
                | About
            li
              a href="#contact"
                | Contact
    .container
      - flash.each do |name, msg|
        = content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable" do
          button.close type="button" data-dismiss="alert" aria-hidden="true"
            | &times;
          = msg
      = yield

app/views/pages/one_column.html.slim
.row
  .column-xs-12 data-content-area='main-area'